//! Deciding whether a filename was generated by a bot or typed by a
//! human, and which files must never be renamed regardless.
//!
//! A port of SABnzbd's `is_probably_obfuscated()` from
//! `deobfuscate_filenames.py`. It exists as a guard: without it the
//! fallback rename in `postprocess.zig` would cheerfully destroy
//! correctly-named releases.
//!
//! # No regex engine
//!
//! Go used four compiled `regexp`s. There is no regex engine in the Zig
//! standard library and pulling one in for four fixed patterns would be
//! a dependency with a much larger attack surface than the patterns
//! themselves. Each is a handful of lines of character classification,
//! written out below with the original pattern in the comment so the two
//! can be compared.
//!
//! # The bias
//!
//! `isProbablyObfuscated` returns *false* when unsure. A false positive
//! renames a correctly-named file and the operator loses the release
//! name; a false negative leaves an ugly hex filename that the operator
//! can fix by hand. The asymmetry is the whole reason the "hand-named
//! shape" short-circuit exists.

const std = @import("std");
const app_ports = @import("../ports.zig");

/// Extensions that must never be renamed: archive parts, parity, disc
/// structure, and sidecars too small to be "the main file" anyway.
/// SABnzbd's `EXCLUDED_FILE_EXTS`.
pub const excluded_exts = [_][]const u8{
    ".rar", ".par2", ".mts", ".m2ts", ".bdmv", ".vob",
    ".ifo", ".bup",  ".sfv", ".nzb",  ".srt",  ".idx",
    ".sub",
};

/// Directory names that mark a DVD or Blu-ray layout. Renaming anything
/// inside one destroys the disc.
pub const disc_markers = [_][]const u8{ "VIDEO_TS", "AUDIO_TS", "BDMV", "CERTIFICATE" };

fn eqlIgnoreCase(a: []const u8, b: []const u8) bool {
    return std.ascii.eqlIgnoreCase(a, b);
}

/// The extension including its dot, or "" when there is none. Matches
/// `filepath.Ext`: the last dot in the basename, nothing before it.
pub fn extensionOf(name: []const u8) []const u8 {
    const base = std.fs.path.basename(name);
    const dot = std.mem.lastIndexOfScalar(u8, base, '.') orelse return "";
    return base[dot..];
}

/// The basename with its extension removed.
pub fn stemOf(name: []const u8) []const u8 {
    const base = std.fs.path.basename(name);
    const ext = extensionOf(base);
    return base[0 .. base.len - ext.len];
}

pub fn isExcludedExt(name: []const u8) bool {
    const ext = extensionOf(name);
    if (ext.len == 0) return false;
    for (excluded_exts) |e| {
        if (eqlIgnoreCase(e, ext)) return true;
    }
    return false;
}

fn isHexDigit(c: u8) bool {
    return (c >= '0' and c <= '9') or (c >= 'a' and c <= 'f') or (c >= 'A' and c <= 'F');
}

/// `^[a-f0-9]{32}$` — the canonical obfuscated name: a bare MD5.
fn isHex32(s: []const u8) bool {
    if (s.len != 32) return false;
    for (s) |c| {
        if (!isHexDigit(c)) return false;
    }
    return true;
}

/// `^[a-f0-9.]{40,}$` — a long chain of hex and dots, which is what a
/// bot produces when it splits an obfuscated name across "extensions".
fn isHexDotsLong(s: []const u8) bool {
    if (s.len < 40) return false;
    for (s) |c| {
        if (!isHexDigit(c) and c != '.') return false;
    }
    return true;
}

/// `[a-f0-9]{30}` anywhere in the string.
fn hasHex30Run(s: []const u8) bool {
    var run: usize = 0;
    for (s) |c| {
        if (isHexDigit(c)) {
            run += 1;
            if (run >= 30) return true;
        } else {
            run = 0;
        }
    }
    return false;
}

fn isWordChar(c: u8) bool {
    return std.ascii.isAlphanumeric(c) or c == '_';
}

/// `\[[\w+]+\]` — bracketed tokens of word characters and `+`, as used
/// by the indexing bots that pair a hex blob with `[1/12]`-style tags.
pub fn countBracketTokens(s: []const u8) usize {
    var n: usize = 0;
    var i: usize = 0;
    while (i < s.len) : (i += 1) {
        if (s[i] != '[') continue;
        var j = i + 1;
        while (j < s.len and (isWordChar(s[j]) or s[j] == '+')) j += 1;
        // At least one character inside, and a closing bracket.
        if (j > i + 1 and j < s.len and s[j] == ']') {
            n += 1;
            i = j;
        }
    }
    return n;
}

/// Whether the name has the structural cues of something a human typed:
/// mixed case with separators, several separators, letters plus digits
/// with separators, or a capitalised proper-noun shape.
///
/// When this trips, `isProbablyObfuscated` short-circuits to false even
/// if a weaker pattern would otherwise have matched.
pub fn hasHandNamedShape(name: []const u8) bool {
    var upper: usize = 0;
    var lower: usize = 0;
    var digits: usize = 0;
    var seps: usize = 0;
    for (name) |c| {
        if (std.ascii.isUpper(c)) {
            upper += 1;
        } else if (std.ascii.isLower(c)) {
            lower += 1;
        } else if (std.ascii.isDigit(c)) {
            digits += 1;
        } else if (c == '.' or c == ' ' or c == '_' or c == '-') {
            seps += 1;
        }
    }
    if (upper >= 2 and lower >= 2 and seps >= 1) return true;
    if (seps >= 3) return true;
    const letters = upper + lower;
    if (letters >= 4 and digits >= 4 and seps >= 1) return true;
    if (letters > 0 and name.len > 0 and std.ascii.isUpper(name[0])) {
        const ratio = @as(f64, @floatFromInt(upper)) / @as(f64, @floatFromInt(letters));
        if (ratio < 0.25) return true;
    }
    return false;
}

/// Whether the name looks machine-generated.
pub fn isProbablyObfuscated(name: []const u8) bool {
    const stem = stemOf(name);

    if (isHex32(stem)) return true;
    if (isHexDotsLong(stem)) return true;
    if (hasHex30Run(stem) and countBracketTokens(stem) >= 2) return true;
    if (stem.len >= 7 and std.ascii.eqlIgnoreCase(stem[0..7], "abc.xyz")) return true;

    // Everything below here is a guess, and a wrong guess destroys a
    // release name. Say no.
    return false;
}

/// Whether `dir` contains a recognisable DVD or Blu-ray layout.
pub fn isDiscStructure(fs: app_ports.Filesystem, dir: []const u8) bool {
    var buf: [1024]u8 = undefined;
    for (disc_markers) |marker| {
        const p = std.fmt.bufPrint(&buf, "{s}/{s}", .{ dir, marker }) catch continue;
        if (fs.isDir(p)) return true;
    }
    return false;
}

// ---------------------------------------------------------------------
// Tests — internal/app/deliver/obfuscation_test.go
// ---------------------------------------------------------------------

const testing = std.testing;

test "obfuscation detection matches the SABnzbd cases" {
    const cases = [_]struct { []const u8, bool }{
        // Clear obfuscation.
        .{ "abcdef1234567890abcdef1234567890.mkv", true },
        .{ "aaaabbbbccccddddeeeeffff00001111.mkv", true },
        .{ "abc.xyz.something.mkv", true },

        // Hand-named: mixed case plus separators.
        .{ "Great.Movie.2020.1080p.WEB-DL.x264.mkv", false },
        .{ "Some_Series_S01E01_Title.mkv", false },
        .{ "My Movie (2019).mkv", false },

        // A typical all-lowercase scene release.
        .{ "some.lower.case.movie.2020.mkv", false },

        // Hex-looking but too short for the 32-hex rule, and structured
        // like a real name.
        .{ "deadbeef.feedface.zip", false },

        // Short and random: neither obfuscated nor hand-named-shaped.
        // The bias says leave it alone.
        .{ "xyz.mkv", false },
    };
    for (cases) |c| {
        try testing.expectEqual(c[1], isProbablyObfuscated(c[0]));
    }
}

test "the 32-hex rule is exact about length and alphabet" {
    // 31 and 33 hex characters are not the pattern.
    try testing.expect(!isProbablyObfuscated(("a" ** 31) ++ ".mkv"));
    try testing.expect(isProbablyObfuscated(("a" ** 32) ++ ".mkv"));
    try testing.expect(!isProbablyObfuscated(("a" ** 33) ++ ".mkv"));
    // A non-hex letter breaks it.
    try testing.expect(!isProbablyObfuscated("g" ++ ("a" ** 31) ++ ".mkv"));
}

test "a long hex-and-dots chain is obfuscated" {
    // 40+ characters of nothing but hex and dots.
    const name = "ab.cd.ef.01.23.45.67.89.ab.cd.ef.01.23.45.mkv";
    try testing.expect(isProbablyObfuscated(name));
    // The same length with a real word in it is not.
    try testing.expect(!isProbablyObfuscated("ab.cd.movie.01.23.45.67.89.ab.cd.ef.01.23.45.mkv"));
}

test "a 30-hex run needs two bracket tokens to count" {
    const hex30 = "a" ** 30;
    try testing.expect(!isProbablyObfuscated(hex30 ++ ".mkv"));
    try testing.expect(!isProbablyObfuscated(hex30 ++ "[1].mkv"));
    try testing.expect(isProbablyObfuscated(hex30 ++ "[1][of+12].mkv"));
}

test "bracket tokens are counted, not just found" {
    try testing.expectEqual(@as(usize, 0), countBracketTokens("no brackets"));
    try testing.expectEqual(@as(usize, 0), countBracketTokens("[]"));
    try testing.expectEqual(@as(usize, 0), countBracketTokens("[unclosed"));
    try testing.expectEqual(@as(usize, 1), countBracketTokens("[abc_1]"));
    try testing.expectEqual(@as(usize, 2), countBracketTokens("[a][b+c]"));
    // A non-word character inside breaks the token.
    try testing.expectEqual(@as(usize, 0), countBracketTokens("[a b]"));
}

test "hand-named shapes are recognised" {
    try testing.expect(hasHandNamedShape("Great.Movie"));
    try testing.expect(hasHandNamedShape("a.b.c.d"));
    try testing.expect(hasHandNamedShape("abcd.1234"));
    try testing.expect(!hasHandNamedShape("abcdef"));
    try testing.expect(!hasHandNamedShape(""));
}

test "excluded extensions are case blind and cover the archive set" {
    const excluded = [_][]const u8{
        "movie.rar",   "movie.RAR", "set.vol01.par2", "disc.bdmv",
        "chapter.vob", "index.ifo", "subs.srt",       "a.SUB",
    };
    for (excluded) |n| try testing.expect(isExcludedExt(n));

    const allowed = [_][]const u8{ "movie.mkv", "audio.mp3", "podcast.m4a", "noext" };
    for (allowed) |n| try testing.expect(!isExcludedExt(n));
}

test "extension and stem follow filepath.Ext" {
    try testing.expectEqualStrings(".mkv", extensionOf("/a/b/movie.mkv"));
    try testing.expectEqualStrings("movie", stemOf("/a/b/movie.mkv"));
    try testing.expectEqualStrings("", extensionOf("noext"));
    try testing.expectEqualStrings("noext", stemOf("noext"));
    // A dot in a parent directory is not the file's extension.
    try testing.expectEqualStrings("", extensionOf("/a.b/movie"));
    try testing.expectEqualStrings("a.b", stemOf("a.b.c"));
}

test "disc structure is detected by its marker directories" {
    var fs = app_ports.FakeFs.init(testing.allocator);
    defer fs.deinit();
    const f = fs.filesystem();

    try fs.addDir("/rel");
    try testing.expect(!isDiscStructure(f, "/rel"));

    try fs.addDir("/rel/VIDEO_TS");
    try testing.expect(isDiscStructure(f, "/rel"));

    try fs.addDir("/bd");
    try fs.addDir("/bd/BDMV");
    try testing.expect(isDiscStructure(f, "/bd"));

    // A *file* named like a marker is not a disc structure.
    try fs.addDir("/fake");
    try fs.addFile("/fake/BDMV", 10);
    try testing.expect(!isDiscStructure(f, "/fake"));
}
